spring:
  application:
    name: Accounts
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      schema-locations: classpath:init-test.sql
      mode: always
  h2:
      console:
        enabled: true
        path: /h2-console
server:
  port: 8089
