spring:
  application:
    name: Accounts
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
      console:
        enabled: true
        path: /h2-console
server:
  port: 8089

logging:
  level:
    root: INFO
    ar.edu.unlam.tpi.recomendation_api: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"